app:
  name: boardsite-server
  version: 1.0.0
server:
  base_url: http://localhost
  port: 8000
  origins: "*"
  rpm: 0
  metrics:
    enabled: false
    route: /metrics
    user: admin
    password: admin
cache:
  host: localhost
  port: 6379
session: # default session settings
  max_users: 4
  read_only: false
