app:
  name: boardsite-server
  version: 1.0.0
server:
  host: localhost
  port: 8000
  origins: "*"
  metrics:
    enabled: true
    route: /metrics
    user: admin
    password: admin
cache:
  host: localhost
  port: 6379
session:
  users: 10
  rpm: 10