version: "3.8"
services:
  api:
    build:
      context: .
      target: deploy
    environment: 
      - B_REDIS_HOST=redis
      - B_REDIS_PORT=6379
    ports:
      - "$COMPOSE_HOST_PORT:80"
    depends_on: 
      - redis
  redis:
    image: "redis:alpine"
