version: "3.9"
services:
  api:
    build:
      context: .
      target: deploy
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    command: sh -c "sed '15 s/localhost/redis/' config.yaml > cfg.yaml && ./boardsite -config cfg.yaml"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
