name: Deploy to Testing

on:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".gitignore"
    branches: [ master ]

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Vet files
        run: go vet ./...
      - name: Format files
        run: go fmt ./...
      - name: Run unit tests
        run: go test ./...

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            Port $SSH_PORT
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
            LogLevel ERROR
          END
        env:
          SSH_USER: ${{ secrets.BOARDSITE_TESTING_SSH_USER }}
          SSH_KEY: ${{ secrets.BOARDSITE_TESTING_SSH_KEY }}
          SSH_HOST: ${{ secrets.BOARDSITE_TESTING_SSH_HOST }}
          SSH_PORT: ${{ secrets.BOARDSITE_TESTING_SSH_PORT }}
      - name: Deploy
        run: |
          ssh deploy "cd ~/boardsite-io-deploy && make && make deploy"