name: Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Vet, format and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Download dependencies
        run: go mod download
      - name: Vet files
        run: go vet ./...
      - name: Go mod tidy
        run: |
          go mod tidy
          git diff --exit-code $(git rev-parse HEAD) go.sum go.mod
      - name: Format files
        run: go fmt ./...
      - name: Run unit tests
        run: go test ./...