name: Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Vet files
        run: go vet ./...
      - name: Format files
        run: go fmt ./...
      - name: Build the binary
        run: make build
      - name: Run unit tests
        run: make test